server:
  port: 8080
  servlet:
    context-path: /e-messenger

spring:
  application:
    name: E-messenger

  data:
    mongodb:
      uri: mongodb://localhost:27017/e-messenger

jwt:
  duration:
    access-token: 180
    refresh-token: 4320
  issuer: "e-messenger.com"
  secret-key: "2V1jD5V4U7JOAO0XavZU90W2MNaVfcRrdwEzdFejWfvMAFi5dMGoE5CEJAAY9onL"

api-config:
  title: "E-messenger"
  description: "Chat app"
  version: "1.0.0"

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG